data/air-sal/src/Entity/Prestations.php
<?php

namespace App\Entity;
use Symfony\Component\Serializer\Annotation\MaxDepth;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PrestationsRepository")
 */
class Prestations
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $name;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price_surface;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price_user;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $price_fixed;

    /**
     * @MaxDepth(1)
     * @ORM\ManyToMany(targetEntity="App\Entity\Reservation", mappedBy="Prestations")
     */
    private $reservations;

    /**
     * @MaxDepth(1)
     * @ORM\ManyToMany(targetEntity="App\Entity\Salle", mappedBy="Prestations")
     */
    private $salles;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->salles = new ArrayCollection();
    }

    public function __toString() {
        if( $name = $this->getName() ) {
            return $name;
        }
    
        // if no translation has been added, return empty string instead.
        return '';
    }

    

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPriceSurface(): ?int
    {
        return $this->price_surface;
    }

    public function setPriceSurface(?int $price_surface): self
    {
        $this->price_surface = $price_surface;

        return $this;
    }

    public function getPriceUser(): ?int
    {
        return $this->price_user;
    }

    public function setPriceUser(?int $price_user): self
    {
        $this->price_user = $price_user;

        return $this;
    }

    public function getPriceFixed(): ?int
    {
        return $this->price_fixed;
    }

    public function setPriceFixed(?int $price_fixed): self
    {
        $this->price_fixed = $price_fixed;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->addPrestation($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->contains($reservation)) {
            $this->reservations->removeElement($reservation);
            $reservation->removePrestation($this);
        }

        return $this;
    }

    /**
     * @return Collection|Salle[]
     */
    public function getSalles(): Collection
    {
        return $this->salles;
    }

    public function addSalle(Salle $salle): self
    {
        if (!$this->salles->contains($salle)) {
            $this->salles[] = $salle;
            $salle->addPrestation($this);
        }

        return $this;
    }

    public function removeSalle(Salle $salle): self
    {
        if ($this->salles->contains($salle)) {
            $this->salles->removeElement($salle);
            $salle->removePrestation($this);
        }

        return $this;
    }

}

data/air-sal/src/Form/PrestationsType.php
<?php

namespace App\Form;

use App\Entity\Prestations;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PrestationsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('price_surface')
            ->add('price_user')
            ->add('price_fixed')
            //->add('reservations')
            //->add('salles')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Prestations::class,
        ]);
    }
}

data/air-sal/src/Controller/PrestationsController.php
<?php

namespace App\Controller;

use App\Entity\Prestations;
use App\Form\PrestationsType;
use App\Repository\PrestationsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/prestations")
 */
class PrestationsController extends Controller
{
    /**
     * @Route("/", name="prestations_index", methods="GET")
     */
    public function index(PrestationsRepository $prestationsRepository): Response
    {
        return $this->render('prestations/index.html.twig', ['prestations' => $prestationsRepository->findAll()]);
    }

    /**
     * @Route("/new", name="prestations_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $prestation = new Prestations();
        $form = $this->createForm(PrestationsType::class, $prestation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($prestation);
            $em->flush();

            return $this->redirectToRoute('prestations_index');
        }

        return $this->render('prestations/new.html.twig', [
            'prestation' => $prestation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="prestations_show", methods="GET")
     */
    public function show(Prestations $prestation): Response
    {
        return $this->render('prestations/show.html.twig', ['prestation' => $prestation]);
    }

    /**
     * @Route("/{id}/edit", name="prestations_edit", methods="GET|POST")
     */
    public function edit(Request $request, Prestations $prestation): Response
    {
        $form = $this->createForm(PrestationsType::class, $prestation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('prestations_edit', ['id' => $prestation->getId()]);
        }

        return $this->render('prestations/edit.html.twig', [
            'prestation' => $prestation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="prestations_delete", methods="DELETE")
     */
    public function delete(Request $request, Prestations $prestation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$prestation->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($prestation);
            $em->flush();
        }

        return $this->redirectToRoute('prestations_index');
    }
}

data/air-sal/templates/prestations/_delete_form.html.twig
<form method="post" action="{{ path('prestations_delete', {'id': prestation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ prestation.id) }}">
    <button class="btn button5">Delete</button>
</form>

data/air-sal/templates/prestations/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn button6">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

data/air-sal/templates/prestations/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Prestations{% endblock %}

{% block body %}
    <h1>Edit Prestations</h1>
    <div class="edit-form">
        {{ include('prestations/_form.html.twig', {'button_label': 'Update'}) }}
    </div>

    <a href="{{ path('prestations_index') }}" class="button6">Retourner à la liste</a>

    {{ include('prestations/_delete_form.html.twig') }}
{% endblock %}

data/air-sal/templates/prestations/index.html.twig
{% extends 'tables.html.twig' %}

{% block title %}Prestations index{% endblock %}

{% block content %}
    <h1>Prestations index</h1>

    <table class="table index">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Price_surface</th>
                <th>Price_user</th>
                <th>Price_fixed</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for prestation in prestations %}
            <tr>
                <td>{{ prestation.id }}</td>
                <td>{{ prestation.name }}</td>
                <td>{{ prestation.priceSurface }}</td>
                <td>{{ prestation.priceUser }}</td>
                <td>{{ prestation.priceFixed }}</td>
                <td>
                    <a href="{{ path('prestations_show', {'id': prestation.id}) }}" class="bouton6">show</a>
                    <a href="{{ path('prestations_edit', {'id': prestation.id}) }}" class="bouton6">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if app.user != null and app.user.hasrole("ROLE_ADMIN") %}
        <a href="{{ path('prestations_new') }}" class="bouton6">Create new</a>
    {% endif %}
{% endblock %}

{% block js %}
    <script>
        $(document).ready( function () {
            $('table.table.index').DataTable();
        } );
    </script>
{% endblock %}

data/air-sal/templates/prestations/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Prestations{% endblock %}

{% block body %}
    <h1>Nouvelle Prestations</h1>

    <div class="edit-form">
        {{ include('prestations/_form.html.twig') }}
    </div>

    <a href="{{ path('prestations_index') }}" class="button6">Retourner à la liste</a>
{% endblock %}

data/air-sal/templates/prestations/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Prestations{% endblock %}

{% block body %}
    <h1>Prestations</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ prestation.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ prestation.name }}</td>
            </tr>
            <tr>
                <th>Price_surface</th>
                <td>{{ prestation.priceSurface }}</td>
            </tr>
            <tr>
                <th>Price_user</th>
                <td>{{ prestation.priceUser }}</td>
            </tr>
            <tr>
                <th>Price_fixed</th>
                <td>{{ prestation.priceFixed }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('prestations_index') }}" class="button6">back to list</a>

    <a href="{{ path('prestations_edit', {'id': prestation.id}) }}" class="button6">edit</a>

    {{ include('prestations/_delete_form.html.twig') }}
{% endblock %}